python desc_ddf_gen.py --survey_file_num 0
python desc_ddf_gen.py --survey_file_num 1
python desc_ddf_gen.py --survey_file_num 2
python desc_ddf_gen.py --survey_file_num 3
python desc_ddf_gen.py --survey_file_num 4
python desc_ddf_gen.py --survey_file_num 5
python desc_ddf_gen.py --survey_file_num 6
python desc_ddf_gen.py --survey_file_num 7
python desc_ddf_gen.py --survey_file_num 8
